/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client
// ApiActivityStatus : 
type ApiActivityStatus string

// List of ApiActivityStatus
const (
	UNKNOWN ApiActivityStatus = "UNKNOWN"
	SUBMITTED ApiActivityStatus = "SUBMITTED"
	STARTED ApiActivityStatus = "STARTED"
	SUSPENDED ApiActivityStatus = "SUSPENDED"
	FAILED ApiActivityStatus = "FAILED"
	KILLED ApiActivityStatus = "KILLED"
	SUCCEEDED ApiActivityStatus = "SUCCEEDED"
	ASSUMED_SUCCEEDED ApiActivityStatus = "ASSUMED_SUCCEEDED"
)
