/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// Represents an Impala Query.
type ApiImpalaQuery struct {
	// The query id.
	QueryId string `json:"queryId,omitempty"`
	// The SQL statement for the query.
	Statement string `json:"statement,omitempty"`
	// The query type. The possible values are: DML, DDL, QUERY and UNKNOWN. See the Impala documentation for more details.
	QueryType string `json:"queryType,omitempty"`
	// The query state. The possible values are: CREATED, INITIALIZED, COMPILED, RUNNING, FINISHED, EXCEPTION, and UNKNOWN. See the Impala documentation for more details.
	QueryState string `json:"queryState,omitempty"`
	// The time the query was issued.
	StartTime string `json:"startTime,omitempty"`
	// The time the query finished. If the query hasn't finished then this will return null.
	EndTime string `json:"endTime,omitempty"`
	// The number of rows produced by the query. If the query hasn't completed this will return null.
	RowsProduced float32 `json:"rowsProduced,omitempty"`
	// A map of additional query attributes which is generated by Cloudera Manager.
	Attributes map[string]string `json:"attributes,omitempty"`
	// The user who issued this query.
	User string `json:"user,omitempty"`
	// The host of the Impala Daemon coordinating the query
	Coordinator *ApiHostRef `json:"coordinator,omitempty"`
	// Whether we have a detailed runtime profile available for the query. This profile is available at the endpoint /queries/{QUERY_ID}.
	DetailsAvailable bool `json:"detailsAvailable,omitempty"`
	// The database on which this query was issued.
	Database string `json:"database,omitempty"`
	// The duration of the query in milliseconds. If the query hasn't completed then this will return null.
	DurationMillis float32 `json:"durationMillis,omitempty"`
}
