/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// Represents a user activity, such as a MapReduce job, a Hive query, an Oozie workflow, etc.
type ApiActivity struct {
	// Activity name.
	Name string `json:"name,omitempty"`
	// Activity type. Whether it's an MR job, a Pig job, a Hive query, etc.
	Type_ *ApiActivityType `json:"type,omitempty"`
	// The name of the parent activity.
	Parent string `json:"parent,omitempty"`
	// The start time of this activity.
	StartTime string `json:"startTime,omitempty"`
	// The finish time of this activity.
	FinishTime string `json:"finishTime,omitempty"`
	// Activity id, which is unique within a MapReduce service.
	Id string `json:"id,omitempty"`
	// Activity status.
	Status *ApiActivityStatus `json:"status,omitempty"`
	// The user who submitted this activity.
	User string `json:"user,omitempty"`
	// The user-group of this activity.
	Group string `json:"group,omitempty"`
	// The input data directory of the activity. An HDFS url.
	InputDir string `json:"inputDir,omitempty"`
	// The output result directory of the activity. An HDFS url.
	OutputDir string `json:"outputDir,omitempty"`
	// The mapper class.
	Mapper string `json:"mapper,omitempty"`
	// The combiner class.
	Combiner string `json:"combiner,omitempty"`
	// The reducer class.
	Reducer string `json:"reducer,omitempty"`
	// The scheduler queue this activity is in.
	QueueName string `json:"queueName,omitempty"`
	// The scheduler priority of this activity.
	SchedulerPriority string `json:"schedulerPriority,omitempty"`
}
