/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// A supported external account type. An external account type represents an external authentication source that is used by Cloudera Manager in its APIs to take suitable actions that require authentication to an external service.  An external account type is uniquely identified by a server-generated ID and identifies with a category identifier: e.g. The \"AWS\" category has an account type \"AWS_Access_Key_Authorization\"
type ApiExternalAccountType struct {
	// Represents the immutable name for this account.
	Name string `json:"name,omitempty"`
	// Represents the category of this account.
	CategoryName string `json:"categoryName,omitempty"`
	// Represents the type for this account.
	Type_ string `json:"type,omitempty"`
	// Represents the localized display name for this account.
	DisplayName string `json:"displayName,omitempty"`
	// Represents the localized description for this account type.
	Description string `json:"description,omitempty"`
	// Represents the list of allowed account configs.
	AllowedAccountConfigs *ApiConfigList `json:"allowedAccountConfigs,omitempty"`
}
