/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// Arguments used for the collectDiagnosticData command.
type ApiCollectDiagnosticDataArguments struct {
	// The maximum approximate bundle size of the output file
	BundleSizeBytes float32 `json:"bundleSizeBytes,omitempty"`
	// This parameter is ignored between CM 4.5 and CM 5.7 versions. For versions from CM 4.5 to CM 5.7, use endTime and bundleSizeBytes instead.  For CM 5.7+ versions, startTime is an optional parameter that is with endTime and bundleSizeBytes. This was introduced to perform diagnostic data estimation and collection of global diagnostics data for a certain time range. The start time (in ISO 8601 format) of the period to collection statistics for.
	StartTime string `json:"startTime,omitempty"`
	// The end time (in ISO 8601 format) of the period to collection statistics for.
	EndTime string `json:"endTime,omitempty"`
	// This parameter is ignored as of CM 4.5. INFO logs are always collected. Whether to include INFO level logs. WARN, ERROR, and FATAL level logs are always included.
	IncludeInfoLog bool `json:"includeInfoLog,omitempty"`
	// The support ticket number to attach to this data collection.
	TicketNumber string `json:"ticketNumber,omitempty"`
	// Comments to include with this data collection.
	Comments string `json:"comments,omitempty"`
	// Name of the cluster to collect. If null, collects from all clusters.
	ClusterName string `json:"clusterName,omitempty"`
	// Flag to enable collection of metrics for chart display.
	EnableMonitorMetricsCollection bool `json:"enableMonitorMetricsCollection,omitempty"`
	// List of roles for which to get logs and metrics.  If set, this restricts the roles for log and metrics collection to the list specified.  If empty, the default is to get logs for all roles (in the selected cluster, if one is selected).  Introduced in API v10 of the API.
	Roles []string `json:"roles,omitempty"`
}
