/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// ApiDataContext is the persistent storage/services context exported by the base cluster to be consumed by the compute cluster.
type ApiDataContext struct {
	// 
	Name string `json:"name,omitempty"`
	// 
	DisplayName string `json:"displayName,omitempty"`
	// 
	Nameservice string `json:"nameservice,omitempty"`
	// 
	CreatedTime string `json:"createdTime,omitempty"`
	// 
	LastModifiedTime string `json:"lastModifiedTime,omitempty"`
	// 
	Services []ApiServiceRef `json:"services,omitempty"`
	// 
	ServicesDetails []ApiService `json:"servicesDetails,omitempty"`
	// 
	SupportedServiceTypes []string `json:"supportedServiceTypes,omitempty"`
	// 
	AllowedClusterVersions []ApiMapEntry `json:"allowedClusterVersions,omitempty"`
	// 
	ConfigStalenessStatus *ApiConfigStalenessStatus `json:"configStalenessStatus,omitempty"`
	// 
	ClientConfigStalenessStatus *ApiConfigStalenessStatus `json:"clientConfigStalenessStatus,omitempty"`
	// 
	HealthSummary *ApiHealthSummary `json:"healthSummary,omitempty"`
}
