/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// The response contains a list of applications and warnings.
type ApiYarnApplicationResponse struct {
	// The list of applications for this response.
	Applications []ApiYarnApplication `json:"applications,omitempty"`
	// This list of warnings for this response.
	Warnings []string `json:"warnings,omitempty"`
}
