/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// This is the model for user information in the API, v18 and beyond. <p> Note that any method that returns user information will not contain any password information. The password property is only used when creating or updating users.
type ApiUser2 struct {
	// The username, which is unique within a Cloudera Manager installation.
	Name string `json:"name,omitempty"`
	// Returns the user password. <p> Passwords are not returned when querying user information, so this property will always be empty when reading information from a server.
	Password string `json:"password,omitempty"`
	// A list of ApiAuthRole that this user possesses.
	AuthRoles []ApiAuthRoleRef `json:"authRoles,omitempty"`
	// NOTE: Only available in the \"export\" view
	PwHash string `json:"pwHash,omitempty"`
	// NOTE: Only available in the \"export\" view
	PwSalt float32 `json:"pwSalt,omitempty"`
	// NOTE: Only available in the \"export\" view
	PwLogin bool `json:"pwLogin,omitempty"`
}
