/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// Config Details: The config can either have a value or ref or variable.
type ApiClusterTemplateConfig struct {
	// 
	Name string `json:"name,omitempty"`
	// 
	Value string `json:"value,omitempty"`
	// 
	Ref string `json:"ref,omitempty"`
	// 
	Variable string `json:"variable,omitempty"`
	// 
	AutoConfig bool `json:"autoConfig,omitempty"`
}
