/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// A host template belongs to a cluster and contains a set of role config groups for slave roles (such as DataNodes and TaskTrackers) from services in the cluster. At most one role config group per role type can be present in a host template. Host templates can be applied to fresh hosts (those with no roles on them) in order to create a role for each of the role groups on each host.
type ApiHostTemplate struct {
	// The name of the host template. Unique across clusters.
	Name string `json:"name,omitempty"`
	// Readonly. A reference to the cluster the host template belongs to.
	ClusterRef *ApiClusterRef `json:"clusterRef,omitempty"`
	// The role config groups belonging to this host tempalte.
	RoleConfigGroupRefs []ApiRoleConfigGroupRef `json:"roleConfigGroupRefs,omitempty"`
}
