/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// HDFS specific snapshot policy arguments.
type ApiHdfsSnapshotPolicyArguments struct {
	// The path patterns specifying the paths. Paths matching any of them will be eligible for snapshot creation. <p/> The pattern matching characters that can be specific are those supported by HDFS. please see the documentation for HDFS globs for more details.
	PathPatterns []string `json:"pathPatterns,omitempty"`
}
