/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-api-client

// A clusterRef references a cluster. To operate on the cluster object, use the cluster API with the clusterName as the parameter.
type ApiClusterRef struct {
	// The name of the cluster, which uniquely identifies it in a CM installation.
	ClusterName string `json:"clusterName,omitempty"`
	// The display name of the cluster. This is available from v30.
	DisplayName string `json:"displayName,omitempty"`
}
