/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi
// ApiRoleState : Represents the configured run state of a role.
type ApiRoleState string

// List of ApiRoleState
const (
	HISTORY_NOT_AVAILABLE ApiRoleState = "HISTORY_NOT_AVAILABLE"
	UNKNOWN ApiRoleState = "UNKNOWN"
	STARTING ApiRoleState = "STARTING"
	STARTED ApiRoleState = "STARTED"
	BUSY ApiRoleState = "BUSY"
	STOPPING ApiRoleState = "STOPPING"
	STOPPED ApiRoleState = "STOPPED"
	NA ApiRoleState = "NA"
)
