/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// An externalUserMappingRef references an externalUserMapping.
type ApiExternalUserMappingRef struct {
	// The uuid of the external user mapping, which uniquely identifies it in a CM installation.
	Uuid string `json:"uuid,omitempty"`
	// The name of the mapping.
	Name string `json:"name,omitempty"`
	// The type of the mapping.
	Type_ *ApiExternalUserMappingType `json:"type,omitempty"`
}
