/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// Arguments used for Rolling Upgrade command.
type ApiRollingUpgradeServicesArgs struct {
	// Current CDH Version of the services. Example versions are: \"5.1.0\", \"5.2.2\" or \"5.4.0\"
	UpgradeFromCdhVersion string `json:"upgradeFromCdhVersion,omitempty"`
	// Target CDH Version for the services. The CDH version should already be present and activated on the nodes. Example versions are: \"5.1.0\", \"5.2.2\" or \"5.4.0\"
	UpgradeToCdhVersion string `json:"upgradeToCdhVersion,omitempty"`
	// Number of hosts with slave roles to upgrade at a time. Must be greater than zero. Default is 1.
	SlaveBatchSize float32 `json:"slaveBatchSize,omitempty"`
	// Number of seconds to sleep between restarts of slave host batches.  Must be greater than or equal to 0. Default is 0.
	SleepSeconds float32 `json:"sleepSeconds,omitempty"`
	// The threshold for number of slave host batches that are allowed to fail to restart before the entire command is considered failed.  Must be greater than or equal to 0. Default is 0. <p> This argument is for ADVANCED users only. </p>
	SlaveFailCountThreshold float32 `json:"slaveFailCountThreshold,omitempty"`
	// List of services to upgrade. Only the services that support rolling upgrade should be included.
	UpgradeServiceNames []string `json:"upgradeServiceNames,omitempty"`
}
