/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// This is the model for interactive user session information in the API. <p> A user may have more than one active session. Each such session will have its own session object.
type ApiUserSession struct {
	// The username associated with the session. <p> This will be the same value shown to the logged in user in the UI, which will normally be the same value they typed when logging in, but it is possible that in certain external authentication scenarios, it will differ from that value.
	Name string `json:"name,omitempty"`
	// The remote IP address for the session. <p> This will be the remote IP address for the last request made as part of this session. It is not guaranteed to be the same IP address as was previously used, or the address used to initiate the session.
	RemoteAddr string `json:"remoteAddr,omitempty"`
	// The date and time of the last request received as part of this session. <p> This will be returned in ISO 8601 format from the REST API.
	LastRequest string `json:"lastRequest,omitempty"`
}
