/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-client

// 
type ApiEnableOozieHaArguments struct {
	// IDs of the hosts on which new Oozie Servers will be added.
	NewOozieServerHostIds []string `json:"newOozieServerHostIds,omitempty"`
	// Names of the new Oozie Servers. This is an optional argument, but if provided, it should match the length of host IDs provided.
	NewOozieServerRoleNames []string `json:"newOozieServerRoleNames,omitempty"`
	// Name of the ZooKeeper service that will be used for Oozie HA. This is an optional parameter if the Oozie to ZooKeeper dependency is already set in CM.
	ZkServiceName string `json:"zkServiceName,omitempty"`
	// Hostname of the load balancer used for Oozie HA. Optional if load balancer host and ports are already set in CM.
	LoadBalancerHostname string `json:"loadBalancerHostname,omitempty"`
	// HTTP port of the load balancer used for Oozie HA. Optional if load balancer host and ports are already set in CM.
	LoadBalancerPort float32 `json:"loadBalancerPort,omitempty"`
	// HTTPS port of the load balancer used for Oozie HA when SSL is enabled. This port is only used for oozie.base.url -- the callback is always on HTTP. Optional if load balancer host and ports are already set in CM.
	LoadBalancerSslPort float32 `json:"loadBalancerSslPort,omitempty"`
	// Address of the load balancer used for Oozie HA. This is an optional parameter if this config is already set in CM.
	LoadBalancerHostPort string `json:"loadBalancerHostPort,omitempty"`
}
