/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-client

// Provides information about an HDFS nameservice. <p> Nameservices can be either a stand-alone NameNode, a NameNode paired with a SecondaryNameNode, or a high-availability pair formed by an active and a stand-by NameNode. <p> The following fields are only available in the object's full view: <ul> <li>healthSummary</li> <li>healthChecks</li> </ul>
type ApiNameservice struct {
	// Name of the nameservice.
	Name string `json:"name,omitempty"`
	// Reference to the active NameNode.
	Active *ApiRoleRef `json:"active,omitempty"`
	// Reference to the active NameNode's failover controller, if configured.
	ActiveFailoverController *ApiRoleRef `json:"activeFailoverController,omitempty"`
	// Reference to the stand-by NameNode.
	StandBy *ApiRoleRef `json:"standBy,omitempty"`
	// Reference to the stand-by NameNode's failover controller, if configured.
	StandByFailoverController *ApiRoleRef `json:"standByFailoverController,omitempty"`
	// Reference to the SecondaryNameNode.
	Secondary *ApiRoleRef `json:"secondary,omitempty"`
	// Mount points assigned to this nameservice in a federation.
	MountPoints []string `json:"mountPoints,omitempty"`
	// Requires \"full\" view. The high-level health status of this nameservice.
	HealthSummary *ApiHealthSummary `json:"healthSummary,omitempty"`
	// Requires \"full\" view. List of health checks performed on the nameservice.
	HealthChecks []ApiHealthCheck `json:"healthChecks,omitempty"`
}
