/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// A role represents a specific entity that participate in a service. Examples are JobTrackers, DataNodes, HBase Masters. Each role is assigned a host where it runs on.
type ApiRole struct {
	// The name of the role. Optional when creating a role since API v6. If not specified, a name will be automatically generated for the role.
	Name string `json:"name,omitempty"`
	// The type of the role, e.g. NAMENODE, DATANODE, TASKTRACKER.
	Type_ string `json:"type,omitempty"`
	// A reference to the host where this role runs.
	HostRef *ApiHostRef `json:"hostRef,omitempty"`
	// Readonly. A reference to the parent service.
	ServiceRef *ApiServiceRef `json:"serviceRef,omitempty"`
	// Readonly. The configured run state of this role. Whether it's running, etc.
	RoleState *ApiRoleState `json:"roleState,omitempty"`
	// Readonly. The commission state of this role. Available since API v2.
	CommissionState *ApiCommissionState `json:"commissionState,omitempty"`
	// Readonly. The high-level health status of this role.
	HealthSummary *ApiHealthSummary `json:"healthSummary,omitempty"`
	// Readonly. Expresses whether the role configuration is stale.
	ConfigStale bool `json:"configStale,omitempty"`
	// Readonly. Expresses the role's configuration staleness status. Available since API v6.
	ConfigStalenessStatus *ApiConfigStalenessStatus `json:"configStalenessStatus,omitempty"`
	// Readonly. The list of health checks of this service.
	HealthChecks []ApiHealthCheck `json:"healthChecks,omitempty"`
	// Readonly. The HA status of this role.
	HaStatus *HaStatus `json:"haStatus,omitempty"`
	// Readonly. Link into the Cloudera Manager web UI for this specific role.
	RoleUrl string `json:"roleUrl,omitempty"`
	// Readonly. Whether the role is in maintenance mode. Available since API v2.
	MaintenanceMode bool `json:"maintenanceMode,omitempty"`
	// Readonly. The list of objects that trigger this role to be in maintenance mode. Available since API v2.
	MaintenanceOwners []ApiEntityType `json:"maintenanceOwners,omitempty"`
	// The role configuration. Optional.
	Config *ApiConfigList `json:"config,omitempty"`
	// Readonly. The reference to the role configuration group of this role. Available since API v3.
	RoleConfigGroupRef *ApiRoleConfigGroupRef `json:"roleConfigGroupRef,omitempty"`
	// Readonly. The ZooKeeper server mode for this role. Note that for non-ZooKeeper Server roles this will be null. Available since API v6.
	ZooKeeperServerMode *ZooKeeperServerMode `json:"zooKeeperServerMode,omitempty"`
	// Readonly. The entity status for this role. Available since API v11.
	EntityStatus *ApiEntityStatus `json:"entityStatus,omitempty"`
}
