/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-client

// An authRoleRef to operate on ApiAuthRole object
type ApiAuthRoleRef struct {
	// The display name of the authRole. displayName is optional. If a changed displayName is passed in, it will be ignored.
	DisplayName string `json:"displayName,omitempty"`
	// The name of the authRole. name is available from v32. It is optional, and cannot be modified. Name takes precedence over uuid. If name is absent, uuid will be used for look up.
	Name string `json:"name,omitempty"`
	// The uuid of the authRole, which uniquely identifies it in a CM installation.
	Uuid string `json:"uuid,omitempty"`
}
