/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-client

// Kerberos information of a Cluster or Cloudera Manager.
type ApiKerberosInfo struct {
	// 
	Kerberized bool `json:"kerberized,omitempty"`
	// 
	KdcType string `json:"kdcType,omitempty"`
	// 
	KerberosRealm string `json:"kerberosRealm,omitempty"`
	// 
	KdcHost string `json:"kdcHost,omitempty"`
	// 
	AdminHost string `json:"adminHost,omitempty"`
	// 
	Domain []string `json:"domain,omitempty"`
}
