/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-client

// A HBase snapshot operation error.
type ApiHBaseSnapshotError struct {
	// Name of the table.
	TableName string `json:"tableName,omitempty"`
	// Name of the snapshot.
	SnapshotName string `json:"snapshotName,omitempty"`
	// The location of the snapshot.
	Storage *Storage `json:"storage,omitempty"`
	// Description of the error.
	Error_ string `json:"error,omitempty"`
}
