/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// An HDFS snapshot descriptor.
type ApiHdfsSnapshot struct {
	// Snapshotted path.
	Path string `json:"path,omitempty"`
	// Snapshot name.
	SnapshotName string `json:"snapshotName,omitempty"`
	// Read-only. Fully qualified path for the snapshot version of \"path\". <p/> For example, if a snapshot \"s1\" is present at \"/a/.snapshot/s1, then the snapshot path corresponding to \"s1\" for path \"/a/b\" will be \"/a/.snapshot/s1/b\".
	SnapshotPath string `json:"snapshotPath,omitempty"`
	// Snapshot creation time.
	CreationTime string `json:"creationTime,omitempty"`
}
