/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-client

// Arguments used for Enable NameNode High Availability command.
type ApiEnableNnHaArguments struct {
	// Name of the NameNode role that is going to be made Highly Available.
	ActiveNnName string `json:"activeNnName,omitempty"`
	// Name of the new Standby NameNode role that will be created during the command (Optional).
	StandbyNnName string `json:"standbyNnName,omitempty"`
	// Id of the host on which new Standby NameNode will be created.
	StandbyNnHostId string `json:"standbyNnHostId,omitempty"`
	// List of directories for the new Standby NameNode. If not provided then it will use same dirs as Active NameNode.
	StandbyNameDirList []string `json:"standbyNameDirList,omitempty"`
	// Nameservice to be used while enabling Highly Available. It must be specified if Active NameNode isn't configured with it. If Active NameNode is already configured, then this need not be specified. However, if it is still specified, it must match the existing config for the Active NameNode.
	Nameservice string `json:"nameservice,omitempty"`
	// Name of the journal located on each JournalNodes' filesystem. This can be optionally provided if the config hasn't already been set for the Active NameNode. If this isn't provided and Active NameNode doesn't also have the config, then nameservice is used by default. If Active NameNode already has this configured, then it much match the existing config.
	QjName string `json:"qjName,omitempty"`
	// Name of the FailoverController role to be created on Active NameNode's host (Optional).
	ActiveFcName string `json:"activeFcName,omitempty"`
	// Name of the FailoverController role to be created on Standby NameNode's host (Optional).
	StandbyFcName string `json:"standbyFcName,omitempty"`
	// Name of the ZooKeeper service to be used for Auto-Failover. This MUST be provided if HDFS doesn't have a ZooKeeper dependency. If the dependency is already set, then this should be the name of the same ZooKeeper service, but can also be omitted in that case.
	ZkServiceName string `json:"zkServiceName,omitempty"`
	// Arguments for the JournalNodes to be created during the command. Must be provided only if JournalNodes don't exist already in HDFS.
	Jns []ApiJournalNodeArguments `json:"jns,omitempty"`
	// Boolean indicating if the ZNode should be force initialized if it is already present. Useful while re-enabling High Availability. (Default: TRUE)
	ForceInitZNode bool `json:"forceInitZNode,omitempty"`
	// Boolean indicating if the existing name directories for Standby NameNode should be cleared during the workflow. Useful while re-enabling High Availability. (Default: TRUE)
	ClearExistingStandbyNameDirs bool `json:"clearExistingStandbyNameDirs,omitempty"`
	// Boolean indicating if the existing edits directories for the JournalNodes for the specified nameservice should be cleared during the workflow. Useful while re-enabling High Availability. (Default: TRUE)
	ClearExistingJnEditsDir bool `json:"clearExistingJnEditsDir,omitempty"`
}
