/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// This object is used to represent a role within an ApiParcelUsage.
type ApiParcelUsageRole struct {
	// A reference to the corresponding Role object.
	RoleRef *ApiRoleRef `json:"roleRef,omitempty"`
	// A collection of references to the parcels being used by the role.
	ParcelRefs []ApiParcelRef `json:"parcelRefs,omitempty"`
}
