/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// During import time information related to all the non-base config groups must be provided.
type ApiClusterTemplateRoleConfigGroupInfo struct {
	// 
	RcgRefName string `json:"rcgRefName,omitempty"`
	// 
	Name string `json:"name,omitempty"`
}
