/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// Service information
type ApiClusterTemplateService struct {
	// 
	RefName string `json:"refName,omitempty"`
	// 
	ServiceType string `json:"serviceType,omitempty"`
	// 
	ServiceConfigs []ApiClusterTemplateConfig `json:"serviceConfigs,omitempty"`
	// 
	RoleConfigGroups []ApiClusterTemplateRoleConfigGroup `json:"roleConfigGroups,omitempty"`
	// 
	Roles []ApiClusterTemplateRole `json:"roles,omitempty"`
	// 
	DisplayName string `json:"displayName,omitempty"`
}
