/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi
// ReplicationStrategy : The strategy for distributing the file replication tasks among the mappers of the MR job associated with a replication.
type ReplicationStrategy string

// List of ReplicationStrategy
const (
	STATIC ReplicationStrategy = "STATIC"
	DYNAMIC ReplicationStrategy = "DYNAMIC"
)
