/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-client
// ApiRolesToInclude : Roles to include during a cluster rolling restart.
type ApiRolesToInclude string

// List of ApiRolesToInclude
const (
	SLAVES_ONLY ApiRolesToInclude = "SLAVES_ONLY"
	NON_SLAVES_ONLY ApiRolesToInclude = "NON_SLAVES_ONLY"
	ALL_ROLES ApiRolesToInclude = "ALL_ROLES"
)
