/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// Associates a hostname with its corresponding certificate and private key
type ApiHostCertInfo struct {
	// The FQDN of a host in the deployment.
	Hostname string `json:"hostname,omitempty"`
	// The certificate for this host in PEM format.
	Certificate string `json:"certificate,omitempty"`
	// The private key for this host in PEM format.
	Key string `json:"key,omitempty"`
}
