/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// Arguments to add custom certificates to the Auto-TLS certificate database
type ApiAddCustomCertsArguments struct {
	// The location on disk to store the CMCA directory. If there is already a CMCA created there, it will be backed up, and a new one will be created in its place.
	Location string `json:"location,omitempty"`
	// Whether the following arguments are interpreted as filenames local to the Cloudera Manager host (true, default) or as the actual data for that argument: * hostCerts.hostCert * hostCerts.hostKey  If HTTPS has not been enabled on the Cloudera Manager Admin Console and API, we *strongly* recommend that you pass the arguments as filenames local to the Cloudera Manager host (i.e. set to true) to avoid leaking sensitive information over the wire in plaintext.
	InterpretAsFilenames bool `json:"interpretAsFilenames,omitempty"`
	// A list of HostCertInfo objects, which associate a hostname with the corresponding certificate and private key. Only used if customCA == true.
	HostCerts []ApiHostCertInfo `json:"hostCerts,omitempty"`
}
