/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-client

// Models audit events from both CM and CM managed services like HDFS, HBase and Hive. Audits for CM managed services are retrieved from Cloudera Navigator server.
type ApiAudit struct {
	// When the audit event was captured.
	Timestamp string `json:"timestamp,omitempty"`
	// Service name associated with this audit.
	Service string `json:"service,omitempty"`
	// The user who performed this operation.
	Username string `json:"username,omitempty"`
	// The impersonating user (or the proxy user) who submitted this operation. This is usually applicable when using services like Oozie or Hue, who can be configured to impersonate other users and submit jobs.
	Impersonator string `json:"impersonator,omitempty"`
	// The IP address that the client connected from.
	IpAddress string `json:"ipAddress,omitempty"`
	// The command/operation that was requested.
	Command string `json:"command,omitempty"`
	// The resource that the operation was performed on.
	Resource string `json:"resource,omitempty"`
	// The full text of the requested operation. E.g. the full Hive query. <p> Available since API v5.
	OperationText string `json:"operationText,omitempty"`
	// Whether the operation was allowed or denied by the authorization system.
	Allowed bool `json:"allowed,omitempty"`
}
