/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// A role config group contains roles of the same role type sharing the same configuration. While each role has to belong to a group, a role config group may be empty.  There exists a default role config group for each role type. Default groups cannot be removed nor created.  The name of a role config group is unique and cannot be changed.  The configuration of individual roles may be overridden on role level.
type ApiRoleConfigGroup struct {
	// Readonly. The unique name of this role config group.
	Name string `json:"name,omitempty"`
	// Readonly. The type of the roles in this group.
	RoleType string `json:"roleType,omitempty"`
	// Readonly. Indicates whether this is a base group.
	Base bool `json:"base,omitempty"`
	// The configuration for this group. Optional.
	Config *ApiConfigList `json:"config,omitempty"`
	// The display name of this group.
	DisplayName string `json:"displayName,omitempty"`
	// Readonly. The service reference (service name and cluster name) of this group.
	ServiceRef *ApiServiceRef `json:"serviceRef,omitempty"`
}
