/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cm-client

// Events model noteworthy incidents in Cloudera Manager or the managed Hadoop cluster. An event carries its event category, severity, and a string content. They also have generic attributes, which are free-form key value pairs. Important events may be promoted into alerts.
type ApiEvent struct {
	// A unique ID for this event.
	Id string `json:"id,omitempty"`
	// The content payload of this event.
	Content string `json:"content,omitempty"`
	// When the event was generated.
	TimeOccurred string `json:"timeOccurred,omitempty"`
	// When the event was stored by Cloudera Manager. Events do not arrive in the order that they are generated. If you are writing an event poller, this is a useful field to query.
	TimeReceived string `json:"timeReceived,omitempty"`
	// The category of this event -- whether it is a health event, an audit event, an activity event, etc.
	Category *ApiEventCategory `json:"category,omitempty"`
	// The severity of the event.
	Severity *ApiEventSeverity `json:"severity,omitempty"`
	// Whether the event is promoted to an alert according to configuration.
	Alert bool `json:"alert,omitempty"`
	// A list of key-value attribute pairs.
	Attributes []ApiEventAttribute `json:"attributes,omitempty"`
}
