/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// Provides metadata information about a command.
type ApiCommandMetadata struct {
	// The name of of the command.
	Name string `json:"name,omitempty"`
	// The command arguments schema.  This is in the form of json schema and describes the structure of the command arguments. If null, the command does not take arguments.
	ArgSchema string `json:"argSchema,omitempty"`
}
