/*
 * Cloudera Manager API
 *
 * <h1>Cloudera Manager API v32</h1>       <p>Introduced in Cloudera Manager 6.2.0</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>
 *
 * API version: 6.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cmapi

// A single data point of metric data.
type ApiMetricData struct {
	// When the metric reading was collected.
	Timestamp string `json:"timestamp,omitempty"`
	// The value of the metric.
	Value float32 `json:"value,omitempty"`
}
